### ISSUE TITLE
Using the glyphicon set

### ISSUE THREAD

**Issue by mrozbarry** [justin808/bootstrap-sass-loader#12]
I'm firstly not sure if this is a problem with this loader, or I just have a poor grasp on webpack.

Here is my [app configuration](https://gist.github.com/mrozbarry/5ef6f3db536bccac7ece).

Do I need to use a special loader to get those font files working?  I've been trying to figure this out for two days.  I know I can do this the *wrong* way and just copy the font files into public/fonts, but I want to know the *correct* way to do this.

Any thoughts/ideas?

**Comment by justin808** [comment]
You need a mixin for fonts:

This is how I did this for a sass file used in both a Rails and Webpack Dev Server.

Full details here: https://github.com/justin808/react-webpack-rails-tutorial.

Note, the latests 3.x beta version of node sass is removing the image-url helper. I'm going to follow a similar strategy for that. I'm updating the example today.

Please confirm this fixes your issue and I'll close this issue.

```scss
$rails: false !default;  // defaults to false (e.g. webpack environment)
// Define a custom font.
// Libsass, which is used by the webpack sass loader, does not support font-url()
// so we use url() instead. This is a known issue.
@font-face {
  font-family: 'OpenSans-Light';
  @if $rails {
    src: font-url('OpenSans-Light.ttf') format('truetype');
  } @else {
    src: url('assets/fonts/OpenSans-Light.ttf') format('truetype');
  }
}

@mixin img-url($image) {
  @if $rails {
    image-url($image);
  } @else {
    url('assets/images/' + $image);
  }
}
```
